import { Ionicons } from '@expo/vector-icons';
import { BottomTabNavigationProp } from '@react-navigation/bottom-tabs';
import { useNavigation } from '@react-navigation/native';
import { ScrollView, StyleSheet, Text, View } from 'react-native';
import { ActionButton } from '../components/ActionButton';
import { SurfaceCard } from '../components/SurfaceCard';
import { RootTabParamList } from '../navigation/AppNavigator';
import { colors, radii, spacing, typography } from '../theme';

type QuickTarget = 'Browser' | 'Media' | 'Files' | 'AI';
export function HomeScreen() {
  const navigation = useNavigation<BottomTabNavigationProp<RootTabParamList>>();
  const onOpen = (screen: QuickTarget) => { const routes: Record<QuickTarget, keyof RootTabParamList> = { Browser: 'المتصفح', Media: 'المعرض', Files: 'المعرض', AI: 'مرشد AI' }; navigation.navigate(routes[screen]); };
  return <ScrollView style={styles.screen} contentContainerStyle={styles.content} showsVerticalScrollIndicator={false}>
    <View style={styles.brandRow}><View><Text style={styles.kicker}>مُرشد · S7</Text><Text style={styles.title}>كل ما تحتاجه،<Text style={styles.titleAccent}> في مكان واحد.</Text></Text></View><View style={styles.avatar}><Text style={styles.avatarText}>م</Text></View></View>
    <Text style={styles.greeting}>أهلًا بك. اختر نقطة البداية اليوم.</Text>
    <SurfaceCard accent={colors.teal}><View style={styles.heroTop}><View><Text style={styles.heroLabel}>الوصول السريع</Text><Text style={styles.heroTitle}>تصفح بتركيز</Text><Text style={styles.heroBody}>افتح المواقع والأدوات التي تحتاجها داخل مساحة هادئة.</Text></View><View style={styles.heroIcon}><Ionicons name="compass-outline" size={30} color={colors.tealDark} /></View></View><ActionButton onPress={() => onOpen('Browser')}>فتح المتصفح</ActionButton></SurfaceCard>
    <Text style={styles.sectionTitle}>الأدوات الأساسية</Text>
    <View style={styles.grid}><Tool title="المعرض" detail="صور وفيديو" icon="images-outline" color={colors.coralSoft} iconColor={colors.coral} onPress={() => onOpen('Media')} /><Tool title="الملفات" detail="مساحة منظمة" icon="folder-open-outline" color={colors.blueSoft} iconColor={colors.blue} onPress={() => onOpen('Files')} /><Tool title="مرشد AI" detail="محادثة وذاكرة متصلة" icon="sparkles-outline" color={colors.amberSoft} iconColor={colors.amber} onPress={() => onOpen('AI')} /></View>
    <SurfaceCard accent={colors.amber}><View style={styles.featureRow}><View style={styles.featureIcon}><Ionicons name="sparkles-outline" size={22} color={colors.amber} /></View><View style={styles.featureCopy}><Text style={styles.featureTitle}>قسم المميزات</Text><Text style={styles.featureDetail}>قريبًا سيتوفر قسم المميزات.</Text></View></View></SurfaceCard>
    <Text style={styles.sectionTitle}>ملخص المساحة</Text><SurfaceCard><View style={styles.storageRow}><View style={styles.storageIcon}><Ionicons name="cloud-outline" size={20} color={colors.tealDark} /></View><View style={styles.storageText}><Text style={styles.storageTitle}>التخزين المحلي</Text><Text style={styles.storageDetail}>جاهز لإضافة ملفاتك في المرحلة التالية</Text></View><Text style={styles.storageValue}>0%</Text></View><View style={styles.progress}><View style={styles.progressFill} /></View></SurfaceCard>
  </ScrollView>;
}
function Tool({ title, detail, icon, color, iconColor, onPress }: { title: string; detail: string; icon: keyof typeof Ionicons.glyphMap; color: string; iconColor: string; onPress: () => void }) { return <SurfaceCard><ActionButton tone="quiet" onPress={onPress}><View style={styles.toolInner}><View style={[styles.toolIcon, { backgroundColor: color }]}><Ionicons name={icon} size={20} color={iconColor} /></View><View><Text style={styles.toolTitle}>{title}</Text><Text style={styles.toolDetail}>{detail}</Text></View></View></ActionButton></SurfaceCard>; }
  const styles = StyleSheet.create({ screen: { flex: 1, backgroundColor: colors.surface }, content: { padding: spacing.lg, paddingBottom: spacing.xxl }, brandRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start', marginTop: spacing.sm }, kicker: { ...typography.label, color: colors.tealDark, letterSpacing: 1.2 }, title: { ...typography.display, color: colors.ink, marginTop: spacing.xs }, titleAccent: { color: colors.teal }, greeting: { ...typography.body, color: colors.inkMuted, marginTop: spacing.sm, marginBottom: spacing.xl }, avatar: { width: 42, height: 42, borderRadius: 15, backgroundColor: colors.ink, alignItems: 'center', justifyContent: 'center' }, avatarText: { color: colors.paper, fontSize: 18, fontWeight: '800' }, heroTop: { flexDirection: 'row', alignItems: 'center', marginBottom: spacing.md }, heroLabel: { ...typography.label, color: colors.tealDark }, heroTitle: { ...typography.h2, color: colors.ink, marginTop: 4 }, heroBody: { ...typography.body, color: colors.inkMuted, maxWidth: 230, marginTop: 4 }, heroIcon: { marginLeft: 'auto', width: 58, height: 58, borderRadius: 20, backgroundColor: colors.tealSoft, alignItems: 'center', justifyContent: 'center' }, sectionTitle: { ...typography.h2, color: colors.ink, marginTop: spacing.xl, marginBottom: spacing.sm }, grid: { flexDirection: 'row', gap: spacing.sm }, toolInner: { alignItems: 'flex-start', width: 88 }, toolIcon: { width: 38, height: 38, borderRadius: 13, alignItems: 'center', justifyContent: 'center', marginBottom: spacing.sm }, toolTitle: { ...typography.label, color: colors.ink }, toolDetail: { ...typography.body, color: colors.inkMuted, fontSize: 12, marginTop: 2 }, featureRow: { flexDirection: 'row', alignItems: 'center' }, featureIcon: { width: 42, height: 42, borderRadius: 14, backgroundColor: colors.amberSoft, alignItems: 'center', justifyContent: 'center' }, featureCopy: { flex: 1, marginLeft: spacing.sm }, featureTitle: { ...typography.label, color: colors.ink }, featureDetail: { ...typography.body, color: colors.inkMuted, marginTop: 3 }, storageRow: { flexDirection: 'row', alignItems: 'center' }, storageIcon: { width: 38, height: 38, borderRadius: 13, backgroundColor: colors.tealSoft, alignItems: 'center', justifyContent: 'center' }, storageText: { flex: 1, marginLeft: spacing.sm }, storageTitle: { ...typography.label, color: colors.ink }, storageDetail: { ...typography.body, color: colors.inkMuted, fontSize: 12, marginTop: 2 }, storageValue: { ...typography.h2, color: colors.tealDark }, progress: { height: 8, borderRadius: radii.pill, backgroundColor: colors.tealSoft, marginTop: spacing.md, overflow: 'hidden' }, progressFill: { width: '4%', height: '100%', backgroundColor: colors.teal, borderRadius: radii.pill } });
