import { Ionicons } from '@expo/vector-icons';
import { RuqaaText as Text, RuqaaTextInput as TextInput } from '../components/RuqaaText';
import { useEffect, useMemo, useState } from 'react';
import { ActivityIndicator, RefreshControl, ScrollView, StyleSheet, View } from 'react-native';
import { ActionButton } from '../components/ActionButton';
import { EmptyState } from '../components/EmptyState';
import { SurfaceCard } from '../components/SurfaceCard';
import { firebaseConfigStatus } from '../services/firebase/firebaseConfig';
import { createHubRepository, HubProposal, ProposalStatus, UpdateClass } from '../services/firebase/hubRepository';
import { colors, radii, spacing, typography } from '../theme';

const NEXT_STATUS: Partial<Record<ProposalStatus, ProposalStatus>> = { draft: 'review', review: 'approved', approved: 'published' };

export function HubScreen() {
  const [proposals, setProposals] = useState<HubProposal[]>([]); const [refreshing, setRefreshing] = useState(false); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState<string | null>(null); const [title, setTitle] = useState(''); const [summary, setSummary] = useState(''); const [updateClass, setUpdateClass] = useState<UpdateClass>('dynamic');
  const repository = useMemo(() => createHubRepository(), []);
  const load = async () => { setRefreshing(true); setError(null); try { setProposals(await repository.listRecentProposals()); } catch { setError('تعذر قراءة Firestore. تحقق من تفعيل Firestore وتسجيل دخول مستخدم Admin.'); } finally { setLoading(false); setRefreshing(false); } };
  useEffect(() => { void load(); }, []);
  const createProposal = async () => { if (!title.trim() || !summary.trim()) { setError('اكتب عنوان المقترح وملخصه قبل الحفظ.'); return; } setSaving(true); setError(null); try { await repository.createProposal({ title: title.trim(), summary: summary.trim(), updateClass }); setTitle(''); setSummary(''); await load(); } catch { setError('تعذر إنشاء المسودة. يجب تفعيل Firebase وتسجيل دخول Admin.'); } finally { setSaving(false); } };
  const transition = async (proposal: HubProposal) => { const next = NEXT_STATUS[proposal.status]; if (!next) return; setSaving(true); setError(null); try { await repository.transitionProposal(proposal.id, next); await load(); } catch { setError('تعذر تغيير الحالة. تحقق من صلاحية Admin وقواعد Firestore.'); } finally { setSaving(false); } };
  const counts = { draft: proposals.filter((p) => p.status === 'draft').length, review: proposals.filter((p) => p.status === 'review').length, published: proposals.filter((p) => p.status === 'published').length };
  return <ScrollView style={styles.screen} contentContainerStyle={styles.content} refreshControl={<RefreshControl refreshing={refreshing} onRefresh={load} tintColor={colors.teal} />}>
    <View style={styles.header}><View><Text style={styles.eyebrow}>CONTROL HUB</Text><Text style={styles.title}>مركز التحسينات</Text><Text style={styles.detail}>إدارة المقترحات، الموافقات، والتحديثات من مساحة واحدة.</Text></View><View style={styles.hubIcon}><Ionicons name="git-branch-outline" size={24} color={colors.tealDark} /></View></View>
    <SurfaceCard accent={firebaseConfigStatus.configured ? colors.teal : colors.amber}><View style={styles.statusRow}><View style={[styles.statusDot, { backgroundColor: firebaseConfigStatus.configured ? colors.teal : colors.amber }]} /><View style={styles.statusCopy}><Text style={styles.cardTitle}>{firebaseConfigStatus.configured ? 'Firebase مهيأ' : 'Firebase غير موصل بعد'}</Text><Text style={styles.cardDetail}>{firebaseConfigStatus.configured ? 'العمليات الفعلية تحتاج مستخدمًا مسجلًا بصلاحية Admin وقواعد Firestore.' : 'أضف إعدادات Firebase العامة عبر .env. لا تضع Admin SDK داخل Expo.'}</Text></View></View></SurfaceCard>
    <Text style={styles.sectionTitle}>دورة التحسين</Text><View style={styles.metrics}><Metric icon="create-outline" label="مسودات" value={String(counts.draft)} /><Metric icon="eye-outline" label="مراجعة" value={String(counts.review)} /><Metric icon="rocket-outline" label="منشور" value={String(counts.published)} /></View>
    <Text style={styles.sectionTitle}>مقترح جديد</Text><SurfaceCard><TextInput value={title} onChangeText={setTitle} placeholder="عنوان التحسين" placeholderTextColor={colors.inkFaint} style={styles.input} /><TextInput value={summary} onChangeText={setSummary} placeholder="ملخص واضح لما سيتغير" placeholderTextColor={colors.inkFaint} multiline style={[styles.input, styles.multiline]} /><Text style={styles.fieldLabel}>نوع التحديث</Text><View style={styles.classRow}>{(['dynamic', 'ota', 'native'] as UpdateClass[]).map((kind) => <ActionButton key={kind} tone={updateClass === kind ? 'primary' : 'quiet'} onPress={() => setUpdateClass(kind)}>{kind.toUpperCase()}</ActionButton>)}</View><ActionButton onPress={createProposal}>{saving ? 'جارٍ الحفظ...' : 'حفظ كمسودة'}</ActionButton></SurfaceCard>
    {error ? <SurfaceCard accent={colors.danger}><Text style={styles.cardTitle}>لم تكتمل العملية</Text><Text style={styles.cardDetail}>{error}</Text></SurfaceCard> : null}
    <Text style={styles.sectionTitle}>آخر المقترحات</Text>{loading ? <ActivityIndicator color={colors.teal} /> : proposals.length ? proposals.map((proposal) => <ProposalCard key={proposal.id} proposal={proposal} disabled={saving} onAdvance={() => transition(proposal)} />) : <EmptyState icon="layers-outline" title="لا توجد مقترحات بعد" body="أنشئ أول مسودة من النموذج أعلاه. لن نعرض بيانات تجريبية." />}
    <SurfaceCard><Text style={styles.cardTitle}>تصنيف التحديثات</Text><Text style={styles.cardDetail}>Dynamic للمحتوى والإعدادات، OTA لكود JavaScript المتوافق، وNative لتغييرات Android التي تحتاج APK/AAB جديدًا. نشر EAS يتم من Backend فقط بعد الموافقة.</Text></SurfaceCard>
  </ScrollView>;
}
function Metric({ icon, label, value }: { icon: keyof typeof Ionicons.glyphMap; label: string; value: string }) { return <View style={styles.metric}><Ionicons name={icon} size={19} color={colors.tealDark} /><Text style={styles.metricValue}>{value}</Text><Text style={styles.metricLabel}>{label}</Text></View>; }
function ProposalCard({ proposal, disabled, onAdvance }: { proposal: HubProposal; disabled: boolean; onAdvance: () => void }) { const next = NEXT_STATUS[proposal.status]; return <SurfaceCard><View style={styles.proposalHeader}><Text style={styles.cardTitle}>{proposal.title}</Text><Text style={styles.badge}>{proposal.status}</Text></View><Text style={styles.cardDetail}>{proposal.summary}</Text><Text style={styles.proposalMeta}>{proposal.updateClass} · {proposal.updatedAt}</Text>{next ? <ActionButton tone="quiet" onPress={onAdvance}>{disabled ? '...' : `نقل إلى ${next}`}</ActionButton> : null}</SurfaceCard>; }
const styles = StyleSheet.create({ screen: { flex: 1, backgroundColor: colors.surface }, content: { padding: spacing.lg, paddingBottom: spacing.xxl }, header: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: spacing.xl }, eyebrow: { ...typography.label, color: colors.tealDark, letterSpacing: 1.1 }, title: { ...typography.display, color: colors.ink, marginTop: 3 }, detail: { ...typography.body, color: colors.inkMuted, marginTop: spacing.sm, maxWidth: 280 }, hubIcon: { width: 52, height: 52, borderRadius: 18, backgroundColor: colors.tealSoft, alignItems: 'center', justifyContent: 'center' }, statusRow: { flexDirection: 'row', alignItems: 'center' }, statusDot: { width: 10, height: 10, borderRadius: 5, marginRight: spacing.sm }, statusCopy: { flex: 1 }, cardTitle: { ...typography.label, color: colors.ink }, cardDetail: { ...typography.body, color: colors.inkMuted, marginTop: 5 }, sectionTitle: { ...typography.h2, color: colors.ink, marginTop: spacing.xl, marginBottom: spacing.sm }, metrics: { flexDirection: 'row', gap: spacing.sm }, metric: { flex: 1, backgroundColor: colors.paper, borderRadius: radii.md, padding: spacing.md, borderWidth: 1, borderColor: colors.line }, metricValue: { ...typography.h2, color: colors.ink, marginTop: spacing.sm }, metricLabel: { ...typography.label, color: colors.inkMuted, marginTop: 2 }, input: { ...typography.body, color: colors.ink, borderWidth: 1, borderColor: colors.line, borderRadius: radii.sm, paddingHorizontal: spacing.sm, paddingVertical: spacing.sm, marginBottom: spacing.sm, backgroundColor: colors.surface }, multiline: { minHeight: 76, textAlignVertical: 'top' }, fieldLabel: { ...typography.label, color: colors.inkMuted, marginBottom: spacing.sm }, classRow: { flexDirection: 'row', gap: spacing.xs, marginBottom: spacing.md }, proposalHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' }, badge: { ...typography.label, color: colors.tealDark, backgroundColor: colors.tealSoft, paddingHorizontal: 8, paddingVertical: 4, borderRadius: radii.pill, fontSize: 10 }, proposalMeta: { ...typography.label, color: colors.inkFaint, marginTop: spacing.sm, marginBottom: spacing.sm, fontSize: 10 } });
